version: '3'

volumes:
  node_modules:
  next:
  db_data:

services:
  app:
    image: mkizka/next-fullstack-template
    build: ./app
    command: bash -c "yarn -- && yarn dev"
    ports:
      - 3000:3000
    volumes:
      - node_modules:/app/node_modules
      - next:/app/.next
      - ./app:/app
  db:
    image: "postgres:13-alpine"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
