version: '3'

volumes:
  node_modules:
  next:

services:
  app:
    image: mkizka/next-fullstack-template
    build: ./app
    command: bash -c "yarn -- && yarn dev"
    ports:
      - 3000:3000
    volumes:
      - node_modules:/app/node_modules
      - next:/app/.next
      - ./app:/app
