version: "3"

volumes:
  node_modules:
  next:
  db_data:

services:
  app:
    image: mkizka/next-docker-template
    build: ./app
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - node_modules:/app/node_modules
      - next:/app/.next
      - ./app:/app
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres?schema=public
      - SECRET=secret
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
